#!/usr/bin/env node
'use strict';

// Keep this file dependency-free until the managed environment has been loaded.
const fs = require('node:fs');
const path = require('node:path');
const { createHash, randomBytes } = require('node:crypto');

const GENERATED_BY = 'scripts/windows-dev.cjs';
const ENV_MARKER = `# Generated by ${GENERATED_BY}; schema=1`;
const DATABASE = 'neon_windows_dev';
const USERNAME = 'localadmin';
const STORAGE_KEYS = [
  'SOUL_CHAT_DATA_FILE',
  'USER_PROFILE_DATA_FILE',
  'DOODLE_SHARE_DATA_FILE',
  'DOODLE_UPLOAD_DIRECTORY',
  'DOODLE_REVIEW_DATA_FILE',
  'DOODLE_REVIEW_UPLOAD_DIRECTORY',
  'MOMENT_DATA_FILE',
  'MOMENT_UPLOAD_DIRECTORY'
];

function validatePort(value, name) {
  if (!/^[1-9][0-9]*$/.test(String(value))) throw new Error(`${name} must be an integer between 1 and 65535.`);
  const port = Number(value);
  if (!Number.isSafeInteger(port) || port > 65535) throw new Error(`${name} must be an integer between 1 and 65535.`);
  return port;
}

function locations(rootDir = path.resolve(__dirname, '..')) {
  const root = path.resolve(rootDir);
  return {
    root,
    envFile: path.join(root, '.env.windows.local'),
    credentialsFile: path.join(root, '.data', 'windows-dev', 'credentials.json'),
    releaseId: `windows-dev-${createHash('sha256').update(root).digest('hex').slice(0, 20)}`
  };
}

function expectedEnvironment({ mongoPort, appPort, releaseId }) {
  const validatedMongoPort = validatePort(mongoPort, 'mongoPort');
  const validatedAppPort = validatePort(appPort, 'appPort');
  if (validatedMongoPort === validatedAppPort) throw new Error('MongoDB and the application must use different ports.');
  return {
    NODE_ENV: 'development',
    MONGODB_URI: `mongodb://127.0.0.1:${validatedMongoPort}/${DATABASE}`,
    APP_HOST: '127.0.0.1',
    APP_PORT: String(validatedAppPort),
    ALLOWED_ORIGINS: '',
    NEON_RELEASE_ID: releaseId,
    ...Object.fromEntries(STORAGE_KEYS.map((key) => [key, '']))
  };
}

function assertLocalMongoUri(uri, expectedPort) {
  const port = validatePort(expectedPort, 'mongoPort');
  if (uri !== `mongodb://127.0.0.1:${port}/${DATABASE}`) {
    throw new Error(`Only the managed local MongoDB URI for ${DATABASE} is allowed.`);
  }
  return uri;
}

function parseManagedEnvironment(content) {
  const lines = content.replace(/^\uFEFF/, '').split(/\r?\n/);
  if (lines[0] !== ENV_MARKER) throw new Error('.env.windows.local was not generated by this tool; it will not be overwritten.');
  const env = {};
  for (const line of lines.slice(1)) {
    if (!line || line.startsWith('#')) continue;
    const match = /^([A-Z][A-Z0-9_]*)=(.*)$/.exec(line);
    if (!match || Object.hasOwn(env, match[1])) throw new Error('The managed environment has an invalid or duplicate entry.');
    env[match[1]] = match[2];
  }
  return env;
}

function verifyEnvironment(env, files, requested = {}) {
  const match = /^mongodb:\/\/127\.0\.0\.1:([1-9][0-9]*)\/neon_windows_dev$/.exec(env.MONGODB_URI || '');
  if (!match) throw new Error(`Only the managed local MongoDB URI for ${DATABASE} is allowed.`);
  const mongoPort = validatePort(match[1], 'mongoPort');
  const appPort = validatePort(env.APP_PORT, 'appPort');
  if (requested.mongoPort !== undefined && mongoPort !== validatePort(requested.mongoPort, 'mongoPort')) {
    throw new Error('MongoDB port differs from the existing managed configuration; existing data was left unchanged.');
  }
  if (requested.appPort !== undefined && appPort !== validatePort(requested.appPort, 'appPort')) {
    throw new Error('Application port differs from the existing managed configuration; existing data was left unchanged.');
  }
  const expected = expectedEnvironment({ mongoPort, appPort, releaseId: files.releaseId });
  if (Object.keys(env).length !== Object.keys(expected).length || Object.entries(expected).some(([key, value]) => env[key] !== value)) {
    throw new Error('The managed environment was modified or belongs to a different project path. Restore its generated values before continuing.');
  }
  assertLocalMongoUri(env.MONGODB_URI, mongoPort);
  return { mongoPort, appPort, env };
}

function readCredentials(files) {
  if (!fs.existsSync(files.credentialsFile)) {
    throw new Error(`Saved administrator credentials are missing: ${files.credentialsFile}. Restore this file before continuing.`);
  }
  const saved = JSON.parse(fs.readFileSync(files.credentialsFile, 'utf8'));
  if (saved.schemaVersion !== 1 || saved.generatedBy !== GENERATED_BY || saved.releaseId !== files.releaseId || saved.username !== USERNAME || typeof saved.password !== 'string' || saved.password.length < 8 || saved.password.length > 128) {
    throw new Error('The saved administrator credentials are invalid or belong to a different project path.');
  }
  return saved;
}

function publicInfo(config) {
  return {
    mongoPort: config.mongoPort,
    appPort: config.appPort,
    releaseId: config.releaseId,
    credentialsFile: config.credentialsFile,
    envFile: config.envFile,
    appUrl: `http://127.0.0.1:${config.appPort}`,
    adminUrl: `http://127.0.0.1:${config.appPort}/admin`,
    database: DATABASE,
    username: USERNAME
  };
}

function loadConfiguration({ rootDir, mongoPort, appPort } = {}) {
  const files = locations(rootDir);
  if (!fs.existsSync(files.envFile)) throw new Error('Run the configure command before using the local development environment.');
  const env = parseManagedEnvironment(fs.readFileSync(files.envFile, 'utf8'));
  const checked = verifyEnvironment(env, files, { mongoPort, appPort });
  const credentials = readCredentials(files);
  return { ...files, ...checked, credentials };
}

function configure({ rootDir, mongoPort = 27018, appPort = 3000 } = {}) {
  const files = locations(rootDir);
  const env = expectedEnvironment({ mongoPort, appPort, releaseId: files.releaseId });
  if (fs.existsSync(files.envFile)) return publicInfo(loadConfiguration({ rootDir, mongoPort, appPort }));

  // Persist the password first so an interrupted setup cannot silently replace it.
  fs.mkdirSync(path.dirname(files.credentialsFile), { recursive: true });
  if (fs.existsSync(files.credentialsFile)) {
    readCredentials(files);
  } else {
    fs.writeFileSync(files.credentialsFile, `${JSON.stringify({
      schemaVersion: 1,
      generatedBy: GENERATED_BY,
      releaseId: files.releaseId,
      createdAt: new Date().toISOString(),
      username: USERNAME,
      password: randomBytes(24).toString('base64url')
    }, null, 2)}\n`, { flag: 'wx', mode: 0o600 });
  }
  fs.writeFileSync(files.envFile, `${ENV_MARKER}\n# Local development only. Credentials are stored in .data/windows-dev/credentials.json.\n${Object.entries(env).map(([key, value]) => `${key}=${value}`).join('\n')}\n`, { flag: 'wx', mode: 0o600 });
  return publicInfo(loadConfiguration({ rootDir, mongoPort, appPort }));
}

function applyEnvironment(config, target = process.env) {
  verifyEnvironment(config.env, config);
  for (const [key, value] of Object.entries(config.env)) target[key] = value;
  return target;
}

async function ensureAdmin({ AdminUser, hashPassword, verifyPassword, credentials }) {
  const existing = await AdminUser.findOne({ username: credentials.username }).select('+passwordHash').lean();
  if (existing) {
    if (existing.role !== 'super_admin' || existing.enabled !== true || !(await verifyPassword(credentials.password, existing.passwordHash))) {
      throw new Error('Existing localadmin does not match the saved password, role, or enabled state. No password or session was changed.');
    }
    return 'verified';
  }
  await AdminUser.create({
    username: credentials.username,
    displayName: '本地开发管理员',
    passwordHash: await hashPassword(credentials.password),
    role: 'super_admin',
    enabled: true
  });
  return 'created';
}

async function ensureSample({ CloudMessage, releaseId, now = new Date() }) {
  const messageId = `${releaseId}-welcome`;
  const existing = await CloudMessage.findOne({ $or: [{ messageId }, { password: 'wd' }] }).lean();
  if (existing) return existing.messageId === messageId ? 'present' : 'skipped-code-in-use';
  await CloudMessage.create({
    messageId,
    messageType: 'text',
    content: '欢迎使用 Neon 本地开发环境！MongoDB 和管理员账号已初始化。这是一条本地云传示例，提取码为 wd，有效期 7 天。',
    password: 'wd',
    createdAt: now,
    expireAt: new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000),
    files: []
  });
  return 'created';
}

async function ensureIndexes(models) {
  for (const model of models) {
    await model.createCollection();
    // createIndexes only adds declared indexes and does not drop user indexes.
    await model.createIndexes();
    const indexes = await model.collection.indexes();
    for (const [key, options] of model.schema.indexes()) {
      const actual = indexes.find((index) => JSON.stringify(index.key) === JSON.stringify(key));
      if (!actual || (options.unique === true && actual.unique !== true) || (options.expireAfterSeconds !== undefined && actual.expireAfterSeconds !== options.expireAfterSeconds)) {
        throw new Error(`Expected index is missing or incompatible on ${model.collection.name}.`);
      }
    }
  }
}

async function withDatabase(config, operation) {
  // Loading Mongoose and the application models must happen after this assignment.
  applyEnvironment(config);
  const mongoose = require('mongoose');
  try {
    await mongoose.connect(assertLocalMongoUri(process.env.MONGODB_URI, config.mongoPort), {
      directConnection: true,
      serverSelectionTimeoutMS: 5000
    });
    if (mongoose.connection.db.databaseName !== DATABASE) throw new Error('Unexpected database selected.');
    return await operation(mongoose);
  } finally {
    await mongoose.disconnect();
  }
}

function parseArguments(argv) {
  const command = argv[0];
  if (!['configure', 'info', 'ping', 'seed', 'serve'].includes(command)) {
    throw new Error('Usage: node scripts/windows-dev.cjs <configure|info|ping|seed|serve> [--mongo-port=27018] [--app-port=3000]');
  }
  const options = {};
  for (const argument of argv.slice(1)) {
    const match = /^--(mongo-port|app-port)=(.+)$/.exec(argument);
    if (!match) throw new Error(`Unsupported option: ${argument}`);
    const name = match[1] === 'mongo-port' ? 'mongoPort' : 'appPort';
    if (Object.hasOwn(options, name)) throw new Error(`Duplicate option: ${match[1]}`);
    options[name] = validatePort(match[2], name);
  }
  return { command, options };
}

async function main(argv = process.argv.slice(2)) {
  const { command, options } = parseArguments(argv);
  if (command === 'configure') return configure(options);
  const config = loadConfiguration(options);
  if (command === 'info') return publicInfo(config);
  if (command === 'serve') {
    applyEnvironment(config);
    process.chdir(config.root);
    require('../src/server.js');
    return undefined;
  }
  if (command === 'ping') {
    return withDatabase(config, async (mongoose) => {
      await mongoose.connection.db.admin().command({ ping: 1 });
      return { ...publicInfo(config), status: 'ok' };
    });
  }
  return withDatabase(config, async () => {
    const { AdminUser } = require('../src/server/models/admin');
    const { AdminAudit } = require('../src/server/models/adminAudit');
    const { CloudMessage } = require('../src/server/models/cloud');
    const { hashPassword, verifyPassword } = require('../src/server/admin/auth');
    await ensureIndexes([AdminUser, AdminAudit, CloudMessage]);
    const admin = await ensureAdmin({ AdminUser, hashPassword, verifyPassword, credentials: config.credentials });
    const sample = await ensureSample({ CloudMessage, releaseId: config.releaseId });
    return { ...publicInfo(config), status: 'ok', admin, sample, sampleCode: 'wd' };
  });
}

module.exports = {
  ENV_MARKER, STORAGE_KEYS, applyEnvironment, assertLocalMongoUri, configure,
  ensureAdmin, ensureIndexes, ensureSample, expectedEnvironment, loadConfiguration,
  locations, main, parseArguments, parseManagedEnvironment, publicInfo, validatePort
};

if (require.main === module) {
  main().then((result) => {
    if (result !== undefined) console.log(JSON.stringify(result));
  }).catch((error) => {
    console.error(`Windows development setup failed: ${error.message}`);
    process.exitCode = 1;
  });
}
